import { BarChart3, Bell, BookOpen, CheckCircle2, Edit3, FileClock, LayoutDashboard, Menu, Megaphone, Save, Send, ShieldCheck, Trash2, Users, UserCog, X, Tags, Loader2, Upload, WandSparkles } from 'lucide-react';
import { useState } from 'react';
import { Link, useLocation } from 'wouter';
import { toast } from 'sonner';
import { useAuth } from '@/_core/hooks/useAuth';
import { trpc } from '@/lib/trpc';
import { AdminOperations } from './AdminOperations';
import AdminReports from './AdminReports';
import AdminQuotesManager from './AdminQuotesManager';

const nav = [{ key: 'overview', label: 'نظرة عامة', icon: LayoutDashboard }, { key: 'novels', label: 'الروايات', icon: BookOpen }, { key: 'quotes', label: 'الاقتباسات', icon: WandSparkles }, { key: 'authors', label: 'المؤلفون', icon: Users }, { key: 'genres', label: 'التصنيفات', icon: Tags }, { key: 'users', label: 'المستخدمون والأدوار', icon: UserCog }, { key: 'reports', label: 'التقارير والإحصائيات', icon: BarChart3 }, { key: 'audit', label: 'سجل النشاط', icon: FileClock }, { key: 'trash', label: 'سلة المهملات', icon: Trash2 }, { key: 'notifications', label: 'الإشعارات', icon: Bell }, { key: 'messages', label: 'الرسائل', icon: Send }, { key: 'ads', label: 'إدارة الإعلانات', icon: Megaphone }] as const;
type Section = typeof nav[number]['key'];

function AdminSidebar({ section, setSection, open, onClose }: { section: Section; setSection: (value: Section) => void; open: boolean; onClose: () => void }) { const [, navigate] = useLocation(); return <aside className={`${open ? 'translate-x-0' : 'translate-x-full'} fixed inset-y-0 right-0 z-50 flex w-72 flex-col border-l border-[#222b4a] bg-[#0d142d] text-white transition-transform md:static md:translate-x-0`}><div className="flex h-[78px] items-center justify-between border-b border-white/10 px-6"><Link href="/admin" className="text-lg font-extrabold">رِواية <span className="text-[#8d84f9]">/ admin</span></Link><button onClick={onClose} className="md:hidden"><X size={18} /></button></div><nav className="flex-1 p-4">{nav.map((item) => { const Icon = item.icon; return <button key={item.key} onClick={() => { setSection(item.key); onClose(); if (item.key === 'novels') navigate('/admin/novels'); }} className={`mb-1 flex w-full items-center gap-3 rounded-xl px-3 py-3 text-right text-xs font-semibold transition ${section === item.key ? 'bg-[#6259dd] text-white' : 'text-white/55 hover:bg-white/5 hover:text-white'}`}><Icon size={16} />{item.label}</button>; })}</nav><div className="m-4 rounded-[16px] border border-white/10 bg-white/5 p-4 text-[10px] text-white/55">كل التغييرات تُحفظ مباشرة في Supabase.</div></aside>; }

function Field({ label, value, onChange, type = 'text', required = false, placeholder }: { label: string; value: string | number; onChange: (value: string) => void; type?: string; required?: boolean; placeholder?: string }) { return <label className="grid gap-2 text-xs font-bold"><span>{label}</span><input required={required} type={type} value={value} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} className="h-11 rounded-xl border border-border bg-background px-3 text-sm outline-none transition focus:border-[#8279ee]" /></label>; }

function Overview({ onSelect }: { onSelect: (section: Section) => void }) { const summary = trpc.admin.summary.useQuery(); const cards = summary.data ? [{ label: 'الروايات', value: summary.data.novels, section: 'novels' as const }, { label: 'المؤلفون', value: summary.data.authors, section: 'authors' as const }, { label: 'التصنيفات', value: '—', section: 'genres' as const }, { label: 'المستخدمون', value: 'إدارة', section: 'users' as const }] : []; return <div><div className="mb-8"><h1 className="text-2xl font-extrabold">لوحة التحكم</h1><p className="mt-2 text-xs text-muted-foreground">أدر محتوى المنصة من مكان واحد.</p></div>{summary.isLoading ? <Loader2 className="animate-spin" /> : <div className="grid gap-4 sm:grid-cols-3">{cards.map((card) => <button key={card.label} onClick={() => onSelect(card.section)} className="rounded-[20px] border border-border bg-card p-6 text-right transition hover:-translate-y-0.5 hover:border-[#8279ee]"><span className="text-xs text-muted-foreground">{card.label}</span><strong className="mt-3 block text-3xl font-extrabold">{card.value}</strong><span className="mt-2 block text-[10px] font-bold text-[#675de8]">إدارة المحتوى ←</span></button>)}</div>}</div>; }
