import { Bot, Edit3, Loader2, Save, Trash2, WandSparkles } from 'lucide-react';
import { useState } from 'react';
import { toast } from 'sonner';
import { trpc } from '@/lib/trpc';

export default function AdminQuotesManager() {
  const utils = trpc.useUtils();
  const query = trpc.adminQuotes.list.useQuery();
  const [editing, setEditing] = useState<number | null>(null);
  const [form, setForm] = useState({ quote_text: '', speaker: '', book_title: '', category: '', status: 'published' as 'draft' | 'published' });
  const create = trpc.adminQuotes.create.useMutation({ onSuccess: () => { toast.success('تم حفظ الاقتباس'); reset(); void utils.adminQuotes.list.invalidate(); }, onError: (error) => toast.error(error.message) });
  const update = trpc.adminQuotes.update.useMutation({ onSuccess: () => { toast.success('تم تحديث الاقتباس'); reset(); void utils.adminQuotes.list.invalidate(); }, onError: (error) => toast.error(error.message) });
  const remove = trpc.adminQuotes.delete.useMutation({ onSuccess: () => { toast.success('تم حذف الاقتباس'); void utils.adminQuotes.list.invalidate(); }, onError: (error) => toast.error(error.message) });
  const improve = trpc.adminQuotes.improve.useMutation({ onSuccess: (result) => { setForm((current) => ({ ...current, quote_text: result.quote, speaker: result.speaker, book_title: result.book, category: result.category })); toast.success(`اقترح AI تحسينًا: ${result.note}`); }, onError: (error) => toast.error(error.message) });
  const reset = () => { setEditing(null); setForm({ quote_text: '', speaker: '', book_title: '', category: '', status: 'published' }); };
  const submit = (event: React.FormEvent) => { event.preventDefault(); const data = { quote_text: form.quote_text, speaker: form.speaker || null, book_title: form.book_title || null, category: form.category || null, status: form.status }; editing ? update.mutate({ id: editing, data }) : create.mutate(data); };
  return <div><div className="mb-8"><h1 className="text-2xl font-extrabold">إدارة الاقتباسات</h1><p className="mt-2 text-xs text-muted-foreground">أضف اقتباسًا مع القائل والكتاب، واستخدم AI لتحسين الصياغة واقتراح التصنيف.</p></div>
    <form onSubmit={submit} className="mb-8 grid gap-4 rounded-[20px] border border-border bg-card p-5">
      <label className="grid gap-2 text-xs font-bold"><span>نص الاقتباس</span><textarea required minLength={3} maxLength={2000} value={form.quote_text} onChange={(event) => setForm({ ...form, quote_text: event.target.value })} className="min-h-32 rounded-xl border border-border bg-background p-3 text-sm leading-7 outline-none focus:border-[#8279ee]" placeholder="اكتب الاقتباس هنا..." /></label>
      <div className="grid gap-4 md:grid-cols-3"><label className="grid gap-2 text-xs font-bold"><span>القائل (اختياري)</span><input value={form.speaker} onChange={(event) => setForm({ ...form, speaker: event.target.value })} className="h-11 rounded-xl border border-border bg-background px-3 text-sm" placeholder="اسم القائل" /></label><label className="grid gap-2 text-xs font-bold"><span>الكتاب (اختياري)</span><input value={form.book_title} onChange={(event) => setForm({ ...form, book_title: event.target.value })} className="h-11 rounded-xl border border-border bg-background px-3 text-sm" placeholder="اسم الرواية أو الكتاب" /></label><label className="grid gap-2 text-xs font-bold"><span>التصنيف</span><input value={form.category} onChange={(event) => setForm({ ...form, category: event.target.value })} className="h-11 rounded-xl border border-border bg-background px-3 text-sm" placeholder="حكمة، حب، غموض..." /></label></div>
      <div className="flex flex-wrap gap-2"><button type="button" disabled={!form.quote_text || improve.isPending} onClick={() => improve.mutate({ quote: form.quote_text, speaker: form.speaker || undefined, book: form.book_title || undefined })} className="inline-flex items-center gap-2 rounded-xl border border-[#8279ee] px-4 py-3 text-xs font-bold text-[#675de8] disabled:opacity-50"><WandSparkles size={15} />{improve.isPending ? 'يحلل الاقتباس...' : 'تحسين واقتراح بالـ AI'}</button><button disabled={create.isPending || update.isPending} className="inline-flex items-center gap-2 rounded-xl bg-[#171e42] px-4 py-3 text-xs font-bold text-white"><Save size={15} />{editing ? 'حفظ التعديل' : 'نشر الاقتباس'}</button>{editing && <button type="button" onClick={reset} className="rounded-xl border border-border px-4 py-3 text-xs font-bold">إلغاء</button>}</div>
    </form>
    <div className="grid gap-3">{query.isLoading ? <Loader2 className="animate-spin" /> : (query.data ?? []).map((item) => <article key={item.id} className="rounded-[18px] border border-border bg-card p-5"><div className="flex items-start gap-3"><Bot size={18} className="mt-1 text-[#675de8]" /><div className="min-w-0 flex-1"><p className="text-sm font-bold leading-7">“{item.quote_text}”</p><p className="mt-2 text-xs text-muted-foreground">{item.speaker || 'القائل غير محدد'} · {item.book_title || 'الكتاب غير محدد'} · {item.category || 'بدون تصنيف'}</p><span className="mt-2 inline-block rounded-full bg-muted px-2 py-1 text-[10px]">{item.status === 'published' ? 'منشور' : 'مسودة'}</span></div><button onClick={() => { setEditing(item.id); setForm({ quote_text: item.quote_text, speaker: item.speaker || '', book_title: item.book_title || '', category: item.category || '', status: item.status }); }} className="rounded-lg p-2 text-[#675de8]" aria-label="تعديل"><Edit3 size={16} /></button><button onClick={() => { if (window.confirm('حذف الاقتباس؟')) remove.mutate({ id: item.id }); }} className="rounded-lg p-2 text-red-500" aria-label="حذف"><Trash2 size={16} /></button></div></article>)}</div>
  </div>;
}
