import { BookOpen, CircleHelp, ExternalLink, Mail, MessageCircle, ShieldCheck, Sparkles } from 'lucide-react';
import { Link } from 'wouter';

const email = 'shenuodaepraam@gmail.com';
const whatsappChannel = 'https://whatsapp.com/channel/0029Vb8nZiV4NViec0r66c0z';

function PageFrame({ eyebrow, title, intro, children }: { eyebrow: string; title: string; intro: string; children: React.ReactNode }) {
  return <main className="container py-14 md:py-20"><div className="mx-auto max-w-4xl"><div className="mb-10 max-w-2xl"><div className="section-label mb-3">{eyebrow}</div><h1 className="text-4xl font-extrabold tracking-[-.07em] md:text-5xl">{title}</h1><p className="mt-5 text-base leading-8 text-muted-foreground">{intro}</p></div><div className="rounded-[28px] border border-border bg-card p-6 shadow-sm md:p-10">{children}</div></div></main>;
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return <section className="border-b border-border py-7 first:pt-0 last:border-0 last:pb-0"><h2 className="text-xl font-extrabold tracking-tight">{title}</h2><div className="mt-3 text-sm leading-8 text-muted-foreground">{children}</div></section>;
}

export function AboutPage() {
  return <PageFrame eyebrow="عن المنصة" title="رِواية، مساحة أهدأ لاكتشاف ما يستحق القراءة" intro="رِواية منصة عربية تساعدك على اكتشاف الروايات وفهم عوالمها واتخاذ قرار قراءة يناسب وقتك وذوقك."><div className="grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-[#f0eeff] p-5 dark:bg-[#24224c]"><Sparkles className="mb-4 text-[#675de8]" size={22} /><h2 className="font-extrabold">اكتشاف أذكى</h2><p className="mt-2 text-sm leading-7 text-muted-foreground">تصفح حسب النوع أو الكاتب أو السلسلة، واستخدم البحث للوصول إلى ما يهمك بسرعة.</p></div><div className="rounded-2xl bg-muted/60 p-5"><BookOpen className="mb-4 text-[#675de8]" size={22} /><h2 className="font-extrabold">معلومات مفيدة</h2><p className="mt-2 text-sm leading-7 text-muted-foreground">نقدم نبذة ومعلومات تنظيمية تساعدك على اختيار الرواية دون حرق الأحداث.</p></div><div className="rounded-2xl bg-muted/60 p-5"><ShieldCheck className="mb-4 text-[#675de8]" size={22} /><h2 className="font-extrabold">منصة مسؤولة</h2><p className="mt-2 text-sm leading-7 text-muted-foreground">رِواية لا تستضيف ملفات الكتب ولا توفر نسخًا غير مرخصة، بل تساعدك على اكتشاف القراءة.</p></div></div><Section title="كيف نختار المحتوى؟">نعمل على تنظيم بيانات الروايات والمؤلفين والتصنيفات والسلاسل في تجربة واضحة. قد تحتوي بعض المعلومات على أخطاء أو تحتاج إلى تحديث، لذلك نرحب بتصحيحاتكم عبر صفحة التواصل.</Section></PageFrame>;
}

export function HowItWorksPage() {
  const steps = [['01', 'ابحث أو تصفح', 'اكتب اسم رواية أو مؤلف، أو ابدأ من التصنيفات والسلاسل والاقتراحات.'], ['02', 'اقرأ التفاصيل', 'افتح صفحة الرواية لمعرفة النبذة، النوع، التقييم، عدد الأجزاء، والمؤلف.'], ['03', 'احفظ ما يعجبك', 'سجل دخولك لإضافة الروايات إلى قائمة القراءة والعودة إليها في أي وقت.'], ['04', 'اكتشف أكثر', 'استخدم صفحة اكتشف للوصول إلى اقتراحات جديدة قريبة من اهتماماتك.']];
  return <PageFrame eyebrow="دليل الاستخدام" title="كيف تعمل منصة رِواية؟" intro="صممنا التجربة لتكون بسيطة: اكتشف، افهم، ثم اختر ما تريد قراءته."><div className="grid gap-4 md:grid-cols-2">{steps.map(([number, title, text]) => <div key={number} className="rounded-2xl border border-border p-5"><span className="text-xs font-bold text-[#675de8]">{number}</span><h2 className="mt-3 font-extrabold">{title}</h2><p className="mt-2 text-sm leading-7 text-muted-foreground">{text}</p></div>)}</div><Section title="هل توفر رِواية الكتب للقراءة؟">لا. رِواية منصة اكتشاف ومعلومات فقط، ولا تستضيف ملفات الكتب أو تنشر نسخًا غير مرخصة. استخدم روابط الناشرين أو المتاجر الرسمية عندما تكون متاحة.</Section></PageFrame>;
}

export function PrivacyPage() {
  return <PageFrame eyebrow="الخصوصية" title="سياسة الخصوصية" intro="نحترم خصوصيتك ونوضح هنا ما نحتاجه لتشغيل حسابك وتحسين تجربة اكتشاف الروايات."><Section title="ما البيانات التي نجمعها؟">عند إنشاء حساب قد نحتاج إلى اسمك وبريدك الإلكتروني وبيانات المصادقة. كما قد نحتفظ بقائمة القراءة والتفضيلات التي تختار حفظها. لا نطلب بيانات الدفع داخل رِواية لمجرد تصفح المحتوى.</Section><Section title="كيف نستخدم البيانات؟">نستخدم البيانات لتسجيل الدخول، تأكيد البريد، استعادة الحساب، حفظ قائمة القراءة، حماية لوحة الإدارة، وتحسين ترتيب المحتوى. لا نبيع بياناتك ولا نستخدم بريدك لإرسال رسائل تسويقية دون سبب واضح أو موافقة مناسبة.</Section><Section title="الخدمات الخارجية">نستخدم Supabase للمصادقة وقاعدة البيانات، وCloudinary لتخزين أغلفة الروايات التي يرفعها المشرفون. لكل خدمة سياسات خصوصية خاصة بها، ونرسل إليها الحد الأدنى اللازم لتشغيل الميزة.</Section><Section title="حذف الحساب أو طلب تعديل البيانات">لطلب حذف الحساب أو تعديل بياناتك، تواصل معنا عبر <a className="font-bold text-[#675de8]" href={`mailto:${email}`}>{email}</a>. سنراجع الطلب ونتعامل معه وفق البيانات المتاحة ومتطلبات الأمان.</Section><Section title="تحديث السياسة">قد نحدّث هذه السياسة عند إضافة ميزات جديدة. سيظهر تاريخ آخر تحديث في هذه الصفحة عند إجراء تغيير جوهري.</Section></PageFrame>;
}

export function TermsPage() {
  return <PageFrame eyebrow="الاستخدام" title="شروط الاستخدام" intro="باستخدام رِواية، أنت توافق على استخدام المنصة بطريقة قانونية تحترم القراء وحقوق المؤلفين والناشرين."><Section title="طبيعة الخدمة">رِواية دليل لاكتشاف الروايات وتنظيم المعلومات عنها. لا نضمن أن كل معلومة تظل محدثة دائمًا، ونرحب بإرسال التصحيحات والملاحظات.</Section><Section title="الاستخدام المقبول">يُمنع استخدام الموقع للإساءة أو محاولة الوصول غير المصرح به أو تعطيل الخدمة أو رفع محتوى ينتهك حقوق الآخرين. الحسابات الإدارية مخصصة للمستخدمين المصرح لهم فقط.</Section><Section title="الملكية والروابط">أسماء الروايات والمؤلفين والأعمال تعود إلى أصحابها وناشريها. عند وجود روابط خارجية، ينتقل المستخدم إلى خدمة مستقلة تخضع لشروطها الخاصة.</Section><Section title="إيقاف الحساب">يجوز تعليق الحسابات التي تخالف هذه الشروط أو تضر بالمنصة أو المستخدمين. يمكنك التواصل معنا لطلب مراجعة القرار.</Section></PageFrame>;
}

export function ContactPage() {
  return <PageFrame eyebrow="نحن نسمعك" title="تواصل مع رِواية" intro="اقتراح، تصحيح معلومة، تعاون، أو مشكلة في الحساب؟ أرسل لنا رسالة وسنراجعها."><div className="grid gap-4 md:grid-cols-2"><a href={`mailto:${email}`} className="group rounded-2xl border border-border p-6 transition hover:border-[#675de8]"><Mail className="text-[#675de8]" size={24} /><h2 className="mt-4 font-extrabold">البريد الإلكتروني</h2><p className="mt-2 text-sm text-muted-foreground">{email}</p><span className="mt-4 inline-flex items-center gap-2 text-xs font-bold text-[#675de8]">إرسال رسالة <ExternalLink size={13} /></span></a><a href={whatsappChannel} target="_blank" rel="noreferrer" className="group rounded-2xl border border-border p-6 transition hover:border-[#25d366]"><MessageCircle className="text-[#25d366]" size={24} /><h2 className="mt-4 font-extrabold">قناة رِواية على واتساب</h2><p className="mt-2 text-sm text-muted-foreground">تابع التحديثات والاقتراحات الجديدة.</p><span className="mt-4 inline-flex items-center gap-2 text-xs font-bold text-[#25d366]">فتح القناة <ExternalLink size={13} /></span></a></div><Section title="ما الذي نحتاجه في البلاغ؟">اذكر الصفحة أو الرواية المقصودة، وصف المشكلة، وأي تفاصيل تساعدنا على إعادة إنتاجها. لا ترسل كلمات المرور أو رموز التحقق عبر البريد.</Section></PageFrame>;
}

export function ReportPage() {
  return <PageFrame eyebrow="المساعدة" title="الإبلاغ عن مشكلة" intro="ساعدنا على تحسين رِواية بإرسال تصحيح واضح أو بلاغ عن مشكلة تقنية."><div className="rounded-2xl bg-muted/60 p-5"><CircleHelp className="mb-3 text-[#675de8]" size={24} /><p className="text-sm leading-8 text-muted-foreground">أرسل البلاغ إلى <a className="font-bold text-[#675de8]" href={`mailto:${email}?subject=بلاغ%20عن%20مشكلة%20في%20رِواية`}>{email}</a>، ويفضل أن يتضمن عنوانًا مختصرًا، رابط الصفحة، وما توقعت حدوثه وما حدث فعليًا.</p></div><Section title="بلاغات المحتوى">إذا وجدت اسمًا غير صحيح أو غلافًا لا يمثل الرواية أو تصنيفًا يحتاج إلى تعديل، اذكر القيمة الحالية والقيمة المقترحة إن أمكن.</Section><Section title="بلاغات حقوق الملكية">إذا كنت صاحب حق وترى محتوى يحتاج إلى مراجعة، تواصل معنا من البريد نفسه مع شرح واضح للطلب وسنراجعه.</Section></PageFrame>;
}

export function FaqPage() {
  const questions = [['هل أحتاج إلى حساب؟', 'يمكنك تصفح الروايات دون حساب. تحتاج إلى حساب فقط لحفظ قائمة القراءة واستخدام ميزات الحساب.'], ['هل يمكنني قراءة الروايات داخل الموقع؟', 'لا، رِواية لا تستضيف ملفات الكتب. دورها هو الاكتشاف وتقديم المعلومات التنظيمية.'], ['كيف أستعيد كلمة المرور؟', 'من صفحة تسجيل الدخول اختر نسيت كلمة المرور، أدخل بريدك، ثم افتح رابط الاستعادة الذي يصلك.'], ['كيف أصحح معلومة؟', 'راسلنا على البريد الإلكتروني مع رابط الصفحة والتصحيح المقترح.'], ['كيف أتابع جديد رِواية؟', 'يمكنك متابعة قناة واتساب الرسمية من صفحة تواصل معنا.']];
  return <PageFrame eyebrow="الأسئلة الشائعة" title="إجابات سريعة" intro="أهم الأسئلة التي قد تساعدك على استخدام رِواية بثقة."><div className="divide-y divide-border">{questions.map(([question, answer]) => <details key={question} className="py-5 first:pt-0 last:pb-0"><summary className="cursor-pointer list-none font-extrabold">{question}</summary><p className="mt-3 text-sm leading-8 text-muted-foreground">{answer}</p></details>)}</div><div className="mt-8 rounded-2xl bg-[#f0eeff] p-5 text-sm leading-7 text-[#5f56d9] dark:bg-[#24224c] dark:text-[#bcb7ff]">لم تجد إجابتك؟ <Link href="/contact" className="font-extrabold underline">تواصل معنا</Link>.</div></PageFrame>;
}

export const infoRoutes = { AboutPage, HowItWorksPage, PrivacyPage, TermsPage, ContactPage, ReportPage, FaqPage };
