import { ArrowUpLeft, BookOpen, Check, ChevronLeft, Layers3, Plus, Star, Users } from 'lucide-react';
import { useMemo, useState } from 'react';
import { Link, useRoute } from 'wouter';
import { AuthorCard, GenreCard, InfoChip, SectionHeading, BookStat } from '@/components/ExploreCards';
import { NovelCard } from '@/components/NovelCard';
import { Breadcrumbs, PageIntro } from '@/components/SiteShell';
import { authors, findAuthor, findNovel, genres, getAuthorNovels, getGenreNovels, novels, series } from '@/lib/data';
import { toast } from 'sonner';

export function AuthorPage() {
  const [, params] = useRoute('/authors/:slug');
  const author = findAuthor(params?.slug);
  const authorNovels = getAuthorNovels(author.slug).length ? getAuthorNovels(author.slug) : novels.slice(0, 4);
  const [following, setFollowing] = useState(false);
  return <div className="container py-10 md:py-16"><Breadcrumbs items={['المؤلفون', author.name]} /><section className="relative overflow-hidden rounded-[28px] bg-[#11183a] p-6 text-white md:p-10"><div className="absolute -left-10 -top-20 size-72 rounded-full bg-[#766bea]/25 blur-[80px]" /><div className="relative flex flex-col gap-7 md:flex-row md:items-center"><img src={author.avatar} alt={`صورة ${author.name}`} className="size-28 rounded-[26px] object-cover ring-4 ring-white/10 md:size-36" /><div><div className="mb-2 text-[11px] font-bold tracking-[.12em] text-[#aaa4ff]">مؤلف يستحق الاكتشاف</div><h1 className="text-3xl font-extrabold tracking-[-.07em] md:text-5xl">{author.name}</h1><p className="mt-2 text-sm text-white/55">كاتب وروائي عربي</p><div className="mt-5 flex flex-wrap gap-2">{author.genres.map((genre) => <span key={genre} className="rounded-full bg-white/10 px-3 py-1 text-[10px] font-semibold text-white/70">{genre}</span>)}</div></div><button onClick={() => { setFollowing(!following); toast.success(following ? 'أُزيلت المتابعة' : 'ستصلك أعماله الجديدة'); }} className="md:mr-auto inline-flex items-center justify-center gap-2 rounded-xl bg-white px-4 py-3 text-xs font-extrabold text-[#11183a]">{following ? <Check size={15} /> : <Plus size={15} />}{following ? 'تتابعه' : 'تابع المؤلف'}</button></div></section><div className="mt-10 grid gap-8 lg:grid-cols-[1fr_280px]"><div><section><h2 className="mb-3 text-xl font-extrabold">نبذة عن المؤلف</h2><p className="max-w-2xl text-sm leading-8 text-muted-foreground">{author.bio} نحتفظ هنا بمساحة تعريفية قصيرة تساعدك على التعرف على صوته الأدبي قبل التوجه إلى أعماله، دون اختزال تجربته في أرقام فقط.</p></section><section className="mt-12"><SectionHeading title="جميع أعماله" subtitle="اختيارات من الأعمال المتاحة على رِواية" /><div className="mb-5 flex gap-2"><InfoChip>الأحدث</InfoChip><InfoChip tone="slate">الأقدم</InfoChip><InfoChip tone="slate">الأكثر شعبية</InfoChip></div><div className="grid grid-cols-2 gap-5 sm:grid-cols-3">{authorNovels.map((novel) => <NovelCard key={novel.id} novel={novel} />)}</div></section></div><aside className="space-y-3"><BookStat label="عدد الروايات" value={`${author.books}`} icon={<BookOpen size={14} />} /><BookStat label="التصنيفات الأساسية" value={author.genres.join(' · ')} icon={<Layers3 size={14} />} /><BookStat label="عدد السلاسل" value="3" icon={<Users size={14} />} /></aside></div></div>;
}

export function GenrePage() {
  const [, params] = useRoute('/genres/:slug');
  const genre = genres.find((item) => item.slug === params?.slug) ?? genres[0];
  const genreNovels = getGenreNovels(genre.name);
  return <div className="container py-10 md:py-16"><Breadcrumbs items={['التصنيفات', genre.name]} /><div className="mb-12 grid items-end gap-8 md:grid-cols-[1fr_auto]"><PageIntro eyebrow="تصنيف الروايات" title={`اكتشف عالم ${genre.name}`} description={genre.description + ' هنا ستجد عناوين تساعدك تبدأ من الباب الأقرب لمزاجك.'} /><div className="flex gap-3"><BookStat label="رواية" value={`${genre.count}`} /><BookStat label="مؤلف" value="87" /></div></div><div className="mb-8 flex gap-2 border-b border-border pb-3"><InfoChip>الأكثر شعبية</InfoChip><InfoChip tone="slate">الأحدث</InfoChip><InfoChip tone="slate">الأعلى تقييمًا</InfoChip></div><div className="grid grid-cols-2 gap-5 sm:grid-cols-3 lg:grid-cols-5">{(genreNovels.length ? genreNovels : novels.slice(0, 5)).map((novel) => <NovelCard key={novel.id} novel={novel} />)}</div><section className="mt-20"><SectionHeading title="تصنيفات قريبة" subtitle="لو أعجبك هذا الباب، قد تجد نفسك هنا أيضًا." /><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{genres.filter((item) => item.slug !== genre.slug).slice(0, 4).map((item) => <GenreCard key={item.slug} genre={item} />)}</div></section></div>;
}

export function SeriesPage() {
  const [, params] = useRoute('/series/:slug');
  const selected = params?.slug === 'blue-elephant' ? series[1] : series[0];
  return <div className="container py-10 md:py-16"><Breadcrumbs items={['السلاسل', selected.title]} /><section className="grid items-center gap-8 rounded-[28px] bg-[#11183a] p-6 text-white md:grid-cols-[170px_1fr] md:p-10"><img src={selected.cover} alt={`غلاف ${selected.title}`} className="mx-auto aspect-[3/4] w-40 rounded-[20px] object-cover md:mx-0" /><div><div className="mb-2 text-[11px] font-bold uppercase tracking-[.18em] text-[#aaa4ff]">Reading order</div><h1 className="text-3xl font-extrabold tracking-[-.07em] md:text-5xl">{selected.title}</h1><p className="mt-2 text-sm text-white/55">بقلم {selected.author} · {selected.parts} أجزاء · {selected.status}</p><p className="mt-6 max-w-xl text-sm leading-8 text-white/65">رحلة روائية ممتدة، كل جزء منها يضيف طبقة جديدة إلى العالم ويترك لك سؤالًا آخر تكتشفه بنفسك.</p></div></section><section className="mx-auto mt-12 max-w-3xl"><h2 className="mb-7 text-xl font-extrabold">ترتيب القراءة</h2><div className="relative mr-4 border-r border-dashed border-border pr-8">{selected.books.map((book, index) => <Link key={book} href={`/books/${novels.find((novel) => novel.title === book)?.slug ?? 'ard-zikola'}`} className="group relative mb-5 flex items-center justify-between rounded-[18px] border border-border bg-card p-5 last:mb-0"><span className="absolute -right-[45px] grid size-8 place-items-center rounded-full border-4 border-background bg-[#7067ef] text-xs font-bold text-white">0{index + 1}</span><div><span className="text-[10px] font-bold text-[#7067ef]">الجزء 0{index + 1}</span><h3 className="mt-1 text-sm font-extrabold">{book}</h3></div><ChevronLeft size={17} className="text-muted-foreground transition-transform group-hover:-translate-x-1" /></Link>)}</div></section></div>;
}
