import { ArrowUpLeft, BookOpen, Check, ChevronLeft, Layers3, Plus, Users } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link, useRoute } from 'wouter';
import { AuthorCard, GenreCard, InfoChip, SectionHeading, BookStat } from '@/components/ExploreCards';
import { NovelCard } from '@/components/NovelCard';
import { Breadcrumbs, EmptyState, PageIntro } from '@/components/SiteShell';
import { toAuthor, toGenre, toNovel, coverFallback, statusLabels } from '@/lib/data';
import { toast } from 'sonner';
import { trpc } from '@/lib/trpc';
import { BookLoader } from '@/components/BookLoader';

function setProfileSeo(title: string, description: string, type: string, name: string, path: string) {
  document.title = title;
  const url = `${window.location.origin}${path}`;
  const setMeta = (selector: string, attribute: 'name' | 'property', content: string) => {
    let element = document.head.querySelector<HTMLMetaElement>(selector);
    if (!element) { element = document.createElement('meta'); element.setAttribute(attribute, selector.match(/["']([^"']+)["']/)?.[1] ?? ''); document.head.appendChild(element); }
    element.content = content.slice(0, 160);
  };
  setMeta('meta[name="description"]', 'name', description); setMeta('meta[property="og:title"]', 'property', title); setMeta('meta[property="og:description"]', 'property', description); setMeta('meta[property="og:url"]', 'property', url);
  let canonical = document.head.querySelector<HTMLLinkElement>('link[rel="canonical"]'); if (!canonical) { canonical = document.createElement('link'); canonical.rel = 'canonical'; document.head.appendChild(canonical); } canonical.href = url;
  let jsonLd = document.head.querySelector<HTMLScriptElement>('#page-structured-data'); if (!jsonLd) { jsonLd = document.createElement('script'); jsonLd.id = 'page-structured-data'; jsonLd.type = 'application/ld+json'; document.head.appendChild(jsonLd); } jsonLd.textContent = JSON.stringify({ '@context': 'https://schema.org', '@type': type, name, url, description });
}

export function AuthorPage() {
  const [, params] = useRoute('/authors/:slug'); const slug = params?.slug ?? '';
  const authorQuery = trpc.authors.bySlug.useQuery({ slug }, { enabled: Boolean(slug) });
  const novelsQuery = trpc.novels.search.useQuery({ authorSlug: slug, sort: 'popular', limit: 50 }, { enabled: Boolean(slug) });
  const authorsQuery = trpc.authors.list.useQuery(); const [following, setFollowing] = useState(false);
  const author = authorQuery.data ? toAuthor(authorQuery.data) : null;
  useEffect(() => { if (author) setProfileSeo(`${author.name} — المؤلف وأعماله | رِواية`, `${author.name} مؤلف عربي. تعرّف على نبذته وجميع رواياته وأعماله المنشورة على منصة رِواية.`, 'Person', author.name, `/authors/${slug}`); }, [author, slug]);
  if (authorQuery.isLoading) return <Loading />;
  if (!author) return <NotFound label="المؤلف غير موجود" />; const authorNovels = (novelsQuery.data ?? []).map(toNovel);
  return <div className="container py-10 md:py-16"><Breadcrumbs items={['المؤلفون', author.name]} /><section className="relative overflow-hidden rounded-[28px] bg-[#11183a] p-6 text-white md:p-10"><div className="relative flex flex-col gap-7 md:flex-row md:items-center"><img src={author.avatar || coverFallback} alt={`صورة ${author.name}`} className="size-28 rounded-[26px] object-cover md:size-36" /><div><div className="mb-2 text-[11px] font-bold text-[#aaa4ff]">مؤلف يستحق الاكتشاف</div><h1 className="text-3xl font-extrabold md:text-5xl">{author.name}</h1><p className="mt-2 text-sm text-white/55">{author.bio || 'لا توجد نبذة منشورة بعد.'}</p><Link href={`/authors/${slug}/quotes`} className="mt-4 inline-flex rounded-xl bg-white/10 px-4 py-2 text-xs font-bold text-[#d8d5ff] hover:bg-white/20">اقتباسات {author.name}</Link></div><button onClick={() => { setFollowing(!following); toast.success(following ? 'أُزيلت المتابعة' : 'ستصلك أعماله الجديدة'); }} className="md:mr-auto inline-flex items-center justify-center gap-2 rounded-xl bg-white px-4 py-3 text-xs font-extrabold text-[#11183a]">{following ? <Check size={15} /> : <Plus size={15} />}{following ? 'تتابعه' : 'تابع المؤلف'}</button></div></section><div className="mt-10 grid gap-8 lg:grid-cols-[1fr_280px]"><div><section><h2 className="mb-3 text-xl font-extrabold">نبذة عن المؤلف</h2><p className="max-w-2xl text-sm leading-8 text-muted-foreground">{author.bio || 'سيتم تحديث النبذة من لوحة الإدارة.'}</p></section><section className="mt-12"><SectionHeading title="جميع أعماله" subtitle="الأعمال المنشورة في قاعدة بيانات رِواية" /><div className="grid grid-cols-2 gap-5 sm:grid-cols-3">{authorNovels.map((novel) => <NovelCard key={novel.id} novel={novel} />)}</div>{!authorNovels.length && <EmptyState title="لا توجد روايات بعد" description="لم تُربط روايات بهذا المؤلف بعد." />}</section></div><aside className="space-y-3"><BookStat label="عدد الروايات" value={`${author.books}`} icon={<BookOpen size={14} />} /><BookStat label="المؤلفون المتاحون" value={`${authorsQuery.data?.length ?? 0}`} icon={<Users size={14} />} /></aside></div></div>;
}

export function GenrePage() { const [, params] = useRoute('/genres/:slug'); const slug = params?.slug ?? ''; const genreQuery = trpc.genres.bySlug.useQuery({ slug }, { enabled: Boolean(slug) }); const novelsQuery = trpc.novels.search.useQuery({ genreSlug: slug, sort: 'popular', limit: 50 }, { enabled: Boolean(slug) }); const genresQuery = trpc.genres.list.useQuery(); if (genreQuery.isLoading) return <Loading />; const genre = genreQuery.data ? toGenre(genreQuery.data) : null; if (!genre) return <NotFound label="التصنيف غير موجود" />; const items = (novelsQuery.data ?? []).map(toNovel); return <div className="container py-10 md:py-16"><Breadcrumbs items={['التصنيفات', genre.name]} /><div className="mb-12 grid items-end gap-8 md:grid-cols-[1fr_auto]"><PageIntro eyebrow="تصنيف الروايات" title={`اكتشف عالم ${genre.name}`} description={genre.description || 'استكشف الروايات المرتبطة بهذا التصنيف من قاعدة البيانات.'} /><div className="flex gap-3"><BookStat label="رواية" value={`${genre.count}`} /><BookStat label="تصنيف متاح" value={`${genresQuery.data?.length ?? 0}`} /></div></div><div className="grid grid-cols-2 gap-5 sm:grid-cols-3 lg:grid-cols-5">{items.map((novel) => <NovelCard key={novel.id} novel={novel} />)}</div>{!items.length && <EmptyState title="لا توجد روايات بهذا التصنيف" description="أضف روايات من لوحة الإدارة لعرضها هنا." />}</div>; }

  export function SeriesPage() { const [, params] = useRoute('/series/:slug'); const slug = params?.slug ?? ''; const query = trpc.series.bySlug.useQuery({ slug }, { enabled: Boolean(slug) }); if (query.isLoading) return <Loading />; const selected = query.data; if (!selected) return <NotFound label="السلسلة غير موجودة" />; const books = selected.books as Array<{ slug: string; title: string }>; return <div className="container py-10 md:py-16"><Breadcrumbs items={['السلاسل', selected.title]} /><section className="grid items-center gap-8 rounded-[28px] bg-[#11183a] p-6 text-white md:grid-cols-[170px_1fr] md:p-10"><img src={selected.coverUrl || coverFallback} alt={`غلاف ${selected.title}`} className="mx-auto aspect-[3/4] w-40 rounded-[20px] object-cover md:mx-0" /><div><div className="mb-2 text-[11px] font-bold text-[#aaa4ff]">ترتيب القراءة</div><h1 className="text-3xl font-extrabold md:text-5xl">{selected.title}</h1><p className="mt-2 text-sm text-white/55">{books.length} أجزاء · {statusLabels[selected.status] ?? selected.status}</p><p className="mt-6 max-w-xl text-sm leading-8 text-white/65">{selected.description || 'سلسلة روائية محفوظة في قاعدة بيانات رِواية.'}</p></div></section><section className="mx-auto mt-12 max-w-3xl"><h2 className="mb-7 text-xl font-extrabold">ترتيب القراءة</h2><div className="relative mr-4 border-r border-dashed border-border pr-8">{books.map((book, index) => <Link key={book.slug} href={`/books/${book.slug}`} className="group relative mb-5 flex items-center justify-between rounded-[18px] border border-border bg-card p-5"><span className="absolute -right-[45px] grid size-8 place-items-center rounded-full border-4 border-background bg-[#7067ef] text-xs font-bold text-white">{index + 1}</span><div><span className="text-[10px] font-bold text-[#7067ef]">الجزء {index + 1}</span><h3 className="mt-1 text-sm font-extrabold">{book.title}</h3></div><ChevronLeft size={17} className="mr-auto text-muted-foreground" /></Link>)}</div></section></div>; }
function Loading() { return <BookLoader label="نجهز لك تفاصيل الصفحة" />; }
function NotFound({ label }: { label: string }) { return <div className="container py-16"><EmptyState title={label} description="تحقق من الرابط أو أضف المحتوى من لوحة الإدارة." /></div>; }
