import { ArrowLeft, ArrowRight, BookOpen, Quote, Loader2, Search, Share2 } from 'lucide-react';
import { Link, useRoute } from 'wouter';
import { useMemo, useRef, useState } from 'react';
import { PageIntro, Breadcrumbs, EmptyState } from '@/components/SiteShell';
import { trpc } from '@/lib/trpc';
import { toast } from 'sonner';

export default function QuotesPage() {
  const [visibleCount, setVisibleCount] = useState(10);
  const query = trpc.quotes.list.useQuery({ limit: visibleCount, offset: 0 }, { placeholderData: (previous) => previous });
  const [search, setSearch] = useState('');
  const filtered = useMemo(() => (query.data ?? []).filter((item) => `${item.quote_text} ${item.author_name ?? item.speaker ?? ''} ${item.book_title ?? ''} ${item.category ?? ''}`.toLowerCase().includes(search.toLowerCase().trim())), [query.data, search]);
  return <div className="container py-10 md:py-16">
    <Breadcrumbs items={['اقتباسات الكتب']} />
    <PageIntro eyebrow="بين السطور" title="اقتباسات الكتب" description="اكتشف اقتباسات عن الحياة والحب والنجاح والفلسفة من كتّاب وروايات مختلفة." /><div className="mb-8 flex flex-wrap items-center gap-3"><div className="flex min-w-[240px] flex-1 items-center gap-3 rounded-2xl border border-border bg-card px-4 py-3"><Search size={18} className="text-[#675de8]" /><input value={search} onChange={(event) => setSearch(event.target.value)} className="min-w-0 flex-1 bg-transparent text-sm outline-none" placeholder="ابحث عن اقتباس أو كاتب أو كتاب..." /></div><Link href="/quotes/categories" className="rounded-2xl border border-[#675de8]/30 bg-[#f0eeff] px-4 py-3 text-xs font-extrabold text-[#675de8]">تصفح التصنيفات</Link></div>
    {query.isLoading ? <div className="flex min-h-56 items-center justify-center gap-2 text-sm text-muted-foreground"><Loader2 className="animate-spin" size={18} /> جارٍ تحميل الاقتباسات...</div> : <div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">
      {filtered.map((item, index) => <Link key={item.id} href={`/quotes/${item.id}`} className="quote-card group relative overflow-hidden rounded-[26px] border border-border bg-card p-6 shadow-[0_18px_50px_-38px_rgba(22,30,70,.5)] transition duration-300 hover:-translate-y-1 hover:shadow-[0_24px_58px_-34px_rgba(91,77,232,.35)]">
        <div className="mb-8 flex items-center justify-between"><span className="grid size-11 place-items-center rounded-2xl bg-[#f0eeff] text-[#675de8] dark:bg-[#24224c] dark:text-[#bcb7ff]"><Quote size={20} /></span><span className="text-[11px] font-bold text-muted-foreground">{String(index + 1).padStart(2, '0')}</span></div>
        <blockquote className="text-lg font-extrabold leading-9 tracking-[-.04em]">“{item.quote_text}”</blockquote>
        <div className="mt-8 flex items-center gap-3 border-t border-border pt-4"><BookOpen size={15} className="text-[#675de8]" /><div>{item.book_slug ? <Link href={`/books/${item.book_slug}`} onClick={(event) => event.stopPropagation()} className="block text-xs font-extrabold hover:text-[#675de8]">{item.book_title}</Link> : <p className="text-xs font-extrabold">{item.book_title || 'مصدر غير محدد'}</p>}{item.author_slug ? <Link href={`/authors/${item.author_slug}`} onClick={(event) => event.stopPropagation()} className="mt-1 block text-[10px] text-muted-foreground hover:text-[#675de8]">{item.author_name}</Link> : <p className="mt-1 text-[10px] text-muted-foreground">{item.author_name || item.speaker || 'القائل غير محدد'}</p>}{item.category && <p className="mt-1 text-[10px] text-muted-foreground">{item.category}</p>}</div></div>
      </Link>)}{!query.isLoading && (query.data?.length ?? 0) >= visibleCount && <button type="button" onClick={() => setVisibleCount((count) => count + 10)} className="mx-auto mt-2 rounded-xl border border-[#675de8]/30 bg-[#f0eeff] px-6 py-3 text-xs font-extrabold text-[#675de8] md:col-span-2 lg:col-span-3">{query.isFetching ? 'جارٍ التحميل...' : 'المزيد من الاقتباسات'}</button>}
    </div>}
    {!query.isLoading && !filtered.length && <div className="rounded-2xl border border-dashed border-border p-10 text-center text-sm text-muted-foreground">لا توجد اقتباسات مطابقة.</div>}
    <div className="mt-12 rounded-[24px] bg-[#171e42] p-7 text-white md:flex md:items-center md:justify-between md:gap-8"><div><p className="text-xs font-bold text-[#c9c4ff]">اكتشف المزيد</p><h2 className="mt-2 text-xl font-extrabold">ابحث عن الرواية التي خرج منها اقتباسك المفضل.</h2></div><Link href="/explore" className="mt-5 inline-flex rounded-xl bg-[#eeeefe] px-5 py-3 text-xs font-extrabold text-[#171e42] md:mt-0">استكشف الروايات</Link></div>
  </div>;
}

function wrapCanvasText(context: CanvasRenderingContext2D, text: string, maxWidth: number) {
  const words = text.trim().split(/\s+/); const lines: string[] = []; let line = '';
  for (const word of words) { const candidate = line ? `${line} ${word}` : word; if (context.measureText(candidate).width > maxWidth && line) { lines.push(line); line = word; } else line = candidate; }
  if (line) lines.push(line); return lines;
}

function QuoteShareButton({ quote }: { quote: any }) {
  const [open, setOpen] = useState(false); const [template, setTemplate] = useState<'night' | 'sand'>('night'); const [preview, setPreview] = useState(''); const [busy, setBusy] = useState(false); const canvasRef = useRef<HTMLCanvasElement>(null);
  const makeImage = async () => { setBusy(true); const canvas = canvasRef.current ?? document.createElement('canvas'); canvas.width = 1080; canvas.height = 1920; const context = canvas.getContext('2d'); if (!context) return; const background = new Image(); background.crossOrigin = 'anonymous'; background.src = `/quote-template-${template}.jpg`; await new Promise<void>((resolve) => { background.onload = () => resolve(); background.onerror = () => resolve(); }); context.drawImage(background, 0, 0, canvas.width, canvas.height); context.direction = 'rtl'; context.textAlign = 'center'; context.textBaseline = 'top'; const maxWidth = 820; const text = `“${quote.quote_text}”`; let fontSize = 60; let lines: string[] = []; do { context.font = `700 ${fontSize}px "Noto Naskh Arabic", "Tahoma", sans-serif`; lines = wrapCanvasText(context, text, maxWidth); fontSize -= lines.length > 8 ? 4 : 0; } while (lines.length > 8 && fontSize > 38); const lineHeight = fontSize * 1.65; const startY = (canvas.height - lines.length * lineHeight) / 2 - 60; context.fillStyle = template === 'night' ? '#f8e6bd' : '#3b2330'; lines.forEach((line, index) => context.fillText(line, canvas.width / 2, startY + index * lineHeight)); context.font = `700 30px "Noto Naskh Arabic", "Tahoma", sans-serif`; context.fillStyle = template === 'night' ? '#e0c98a' : '#8a4c54'; const attribution = [quote.author_name || quote.speaker, quote.book_title].filter(Boolean).join(' · '); if (attribution) context.fillText(`— ${attribution}`, canvas.width / 2, startY + lines.length * lineHeight + 55); context.font = '700 27px Tahoma, sans-serif'; context.fillStyle = template === 'night' ? '#d5b76f' : '#8a4c54'; context.fillText('e7ketha.vercel.app', canvas.width / 2, 1815); const dataUrl = canvas.toDataURL('image/jpeg', 0.94); setPreview(dataUrl); setBusy(false); return dataUrl; };
  const share = async () => { const dataUrl = preview || await makeImage(); if (!dataUrl) return; const response = await fetch(dataUrl); const blob = await response.blob(); const file = new File([blob], `e7ketha-quote-${quote.id}.jpg`, { type: 'image/jpeg' }); const text = `“${quote.quote_text}”\n${window.location.href}`; if (navigator.share && (!navigator.canShare || navigator.canShare({ files: [file] }))) { await navigator.share({ title: 'اقتباس من رِواية', text, files: [file] }); toast.success('تم فتح المشاركة بالصورة'); } else { const whatsapp = `https://wa.me/?text=${encodeURIComponent(`${text}\n\nالصورة مرفقة للتحميل والمشاركة`)}`; window.open(whatsapp, '_blank', 'noopener,noreferrer'); const link = document.createElement('a'); link.href = dataUrl; link.download = file.name; link.click(); toast.success('تم فتح واتساب وتنزيل الصورة'); } };
  return <><button onClick={() => { setOpen(true); void makeImage(); }} className="mt-8 inline-flex items-center gap-2 rounded-xl border px-4 py-3 text-xs font-bold"><Share2 size={15} /> مشاركة كصورة</button>{open && <div className="fixed inset-0 z-50 grid place-items-center bg-[#10152b]/70 p-4" role="dialog" aria-modal="true"><div className="max-h-[94vh] w-full max-w-md overflow-y-auto rounded-[28px] bg-background p-4 shadow-2xl"><div className="mb-3 flex items-center justify-between"><h2 className="font-extrabold">شارك الاقتباس بصورة</h2><button type="button" onClick={() => setOpen(false)} className="rounded-lg border px-3 py-1 text-xs font-bold">إغلاق</button></div><div className="grid grid-cols-2 gap-2"><button type="button" onClick={() => { setTemplate('night'); setPreview(''); }} className={`rounded-xl border p-2 text-xs font-bold ${template === 'night' ? 'border-[#c9973e] ring-2 ring-[#c9973e]/30' : ''}`}>ليلي فاخر</button><button type="button" onClick={() => { setTemplate('sand'); setPreview(''); }} className={`rounded-xl border p-2 text-xs font-bold ${template === 'sand' ? 'border-[#a85c55] ring-2 ring-[#a85c55]/30' : ''}`}>ورق دافئ</button></div>{preview ? <img src={preview} alt="معاينة صورة الاقتباس" className="mx-auto mt-3 max-h-[62vh] rounded-2xl object-contain" /> : <div className="grid h-64 place-items-center rounded-2xl bg-muted text-sm text-muted-foreground">{busy ? 'نجهز الصورة...' : 'اضغط مشاركة للمعاينة'}</div>}<div className="mt-3 grid grid-cols-2 gap-2"><button type="button" disabled={busy} onClick={() => void makeImage()} className="rounded-xl border px-3 py-3 text-xs font-bold">تحديث الصورة</button><button type="button" disabled={busy} onClick={() => void share()} className="rounded-xl bg-[#25d366] px-3 py-3 text-xs font-extrabold text-white">واتساب / مشاركة</button></div></div></div>}<canvas ref={canvasRef} className="hidden" /></>;
}

export function QuotePage() {
  const [, params] = useRoute('/quotes/:id');
  const id = Number(params?.id);
  const query = trpc.quotes.byId.useQuery({ id }, { enabled: Number.isInteger(id) && id > 0 });
  const item = query.data;
  const share = async () => { if (navigator.share) await navigator.share({ title: 'اقتباس من رِواية', text: item?.quote_text, url: window.location.href }); else { await navigator.clipboard.writeText(window.location.href); toast.success('تم نسخ الرابط'); } };
  const neighbors = trpc.quotes.neighbors.useQuery({ id }, { enabled: Number.isInteger(id) && id > 0 && Boolean(item), staleTime: 5 * 60 * 1000 });
  if (query.isLoading) return <div className="container py-20 text-center text-muted-foreground">جارٍ تحميل الاقتباس...</div>;
  if (!item) return <div className="container py-16"><EmptyState title="الاقتباس غير موجود" description="قد يكون الاقتباس غير منشور أو أُزيل من الأرشيف." action="تصفح الاقتباسات" /></div>;
  return <div className="container py-10 md:py-20"><Breadcrumbs items={['اقتباسات الكتب', item.book_title || 'اقتباس']} /><button type="button" onClick={() => window.history.back()} className="mb-5 inline-flex items-center gap-2 rounded-xl border border-border px-4 py-2 text-xs font-bold"><ArrowRight size={15} /> رجوع للصفحة السابقة</button><article className="mx-auto max-w-3xl rounded-[30px] border border-border bg-card p-7 shadow-xl md:p-14"><Quote className="mb-8 text-[#675de8]" size={38} /><blockquote className="text-2xl font-extrabold leading-[2] md:text-4xl">“{item.quote_text}”</blockquote><div className="mt-10 border-t border-border pt-6">{item.author_slug ? <Link href={`/authors/${item.author_slug}`} className="font-extrabold text-[#675de8]">{item.author_name}</Link> : <p className="font-extrabold">{item.author_name || item.speaker || 'القائل غير محدد'}</p>}{item.book_slug ? <Link href={`/books/${item.book_slug}`} className="mt-2 block text-sm text-muted-foreground hover:text-[#675de8]">{item.book_title}</Link> : <p className="mt-2 text-sm text-muted-foreground">{item.book_title || 'مصدر غير محدد'}</p>}{item.category && <p className="mt-2 text-xs text-muted-foreground">{item.category}</p>}</div><div className="mt-8 flex flex-wrap items-center justify-between gap-3 border-t border-border pt-6">{neighbors.data?.previous ? <Link href={`/quotes/${neighbors.data.previous.id}`} className="inline-flex items-center gap-2 rounded-xl border px-4 py-3 text-xs font-bold"><ArrowRight size={15} /> السابق</Link> : <span />}{neighbors.data?.next ? <Link href={`/quotes/${neighbors.data.next.id}`} className="inline-flex items-center gap-2 rounded-xl border px-4 py-3 text-xs font-bold">التالي <ArrowLeft size={15} /></Link> : <span />}</div><QuoteShareButton quote={item} /></article></div>;
}
