import { ArrowLeft, BookOpen, Compass, Quote, Tags, Users } from 'lucide-react';
import { Link, useRoute } from 'wouter';
import { useEffect } from 'react';
import { Breadcrumbs, EmptyState, PageIntro } from '@/components/SiteShell';

export const topicDefinitions = [
  { slug: 'arabic-novels', title: 'الروايات العربية', eyebrow: 'دليل القراءة العربي', description: 'دليل شامل لاكتشاف الروايات العربية، من الأعمال الاجتماعية والتاريخية إلى الخيال والرعب والفانتازيا.', intro: 'ابدأ من الخريطة العامة للرواية العربية، ثم انتقل إلى التصنيف أو المؤلف أو السلسلة أو الاقتباس الذي يناسب ذائقتك.', links: [{ href: '/explore', label: 'كل الروايات' }, { href: '/genres/social', label: 'الروايات الاجتماعية' }, { href: '/genres/historical', label: 'الروايات التاريخية' }, { href: '/authors/amr-abdel-hamid', label: 'أعمال المؤلفين' }, { href: '/series/zikola', label: 'السلاسل الروائية' }] },
  { slug: 'horror-novels', title: 'روايات الرعب والغموض', eyebrow: 'أجواء مشوقة ومقلقة', description: 'استكشف روايات الرعب والغموض والقصص النفسية، وانتقل من التصنيف إلى الكتب والاقتباسات ذات الصلة.', intro: 'تصفح الرعب أولًا، ثم وسّع القراءة إلى الغموض والتشويق والروايات النفسية القريبة من هذا المزاج.', links: [{ href: '/genres/horror', label: 'روايات الرعب' }, { href: '/genres/mystery', label: 'روايات الغموض' }, { href: '/genres/suspense', label: 'روايات التشويق' }, { href: '/genres/psychological', label: 'الروايات النفسية' }, { href: '/quotes/categories', label: 'اقتباسات حسب الموضوع' }] },
  { slug: 'fantasy-novels', title: 'روايات الخيال والفانتازيا', eyebrow: 'عوالم تتجاوز المألوف', description: 'دليل للروايات الفانتازية والخيال العلمي والخيال الرمزي، مع روابط مباشرة إلى التصنيفات والكتب والسلاسل.', intro: 'ابدأ بالفانتازيا، ثم انتقل إلى الخيال العلمي والرمزية والأعمال التي تبني عوالم وقوانين مختلفة.', links: [{ href: '/genres/fantasy', label: 'روايات الفانتازيا' }, { href: '/genres/sci-fi', label: 'الخيال العلمي' }, { href: '/genres/symbolic', label: 'الخيال والرمزية' }, { href: '/genres/philosophical', label: 'الخيال الفلسفي' }, { href: '/series', label: 'السلاسل المرتبطة' }] },
  { slug: 'egyptian-literature', title: 'الأدب المصري والرواية الاجتماعية', eyebrow: 'المكان والذاكرة والمجتمع', description: 'مسار موضوعي لاكتشاف الروايات التي تقترب من المجتمع والهوية والتاريخ والتجربة المصرية عبر أعمال المؤلفين المتاحة.', intro: 'استخدم التصنيفات الاجتماعية والتاريخية، ثم افتح صفحات المؤلفين والاقتباسات للوصول إلى الأعمال المرتبطة.', links: [{ href: '/genres/social', label: 'الروايات الاجتماعية' }, { href: '/genres/historical', label: 'الروايات التاريخية' }, { href: '/authors/ahmed-khaled-tawfik', label: 'أعمال المؤلفين' }, { href: '/quotes', label: 'اقتباسات الروايات' }, { href: '/explore', label: 'استكشف المكتبة' }] },
] as const;

function TopicCard({ topic }: { topic: typeof topicDefinitions[number] }) {
  return <Link href={`/topics/${topic.slug}`} className="group rounded-[24px] border border-border bg-card p-6 transition hover:-translate-y-1 hover:border-[#675de8] hover:shadow-lg"><div className="mb-5 flex items-center justify-between"><span className="grid size-11 place-items-center rounded-2xl bg-[#f0eeff] text-[#675de8] dark:bg-[#24224c]"><Compass size={20} /></span><ArrowLeft size={17} className="text-muted-foreground transition group-hover:-translate-x-1 group-hover:text-[#675de8]" /></div><h2 className="text-lg font-extrabold">{topic.title}</h2><p className="mt-3 text-sm leading-7 text-muted-foreground">{topic.description}</p></Link>;
}

export function TopicsPage() {
  useEffect(() => { document.title = 'موضوعات الروايات العربية | 𝐄𝟳𝐤𝐞𝐭𝐡𝐚'; }, []);
  return <div className="container py-10 md:py-16"><Breadcrumbs items={['الموضوعات']} /><PageIntro eyebrow="مركز الاكتشاف" title="اكتشف الروايات حسب الموضوع" description="تغطية مترابطة للروايات العربية: موضوعات، تصنيفات، مؤلفون، سلاسل واقتباسات في مسار قراءة واحد." /><div className="grid gap-5 md:grid-cols-2">{topicDefinitions.map((topic) => <TopicCard key={topic.slug} topic={topic} />)}</div><section className="mt-12 grid gap-4 rounded-[24px] border border-border bg-card p-6 sm:grid-cols-3"><Link href="/explore" className="flex items-center gap-3 rounded-xl p-3 font-bold hover:bg-muted"><BookOpen className="text-[#675de8]" size={18} />كل الروايات</Link><Link href="/authors/ahmed-khaled-tawfik" className="flex items-center gap-3 rounded-xl p-3 font-bold hover:bg-muted"><Users className="text-[#675de8]" size={18} />أعمال المؤلفين</Link><Link href="/quotes/categories" className="flex items-center gap-3 rounded-xl p-3 font-bold hover:bg-muted"><Quote className="text-[#675de8]" size={18} />موضوعات الاقتباسات</Link></section></div>;
}

export function TopicPage() {
  const [, params] = useRoute('/topics/:slug');
  const topic = topicDefinitions.find((item) => item.slug === params?.slug);
  useEffect(() => { if (topic) document.title = `${topic.title} | 𝐄𝟳𝐤𝐞𝐭𝐡𝐚`; }, [topic]);
  if (!topic) return <div className="container py-16"><EmptyState title="الموضوع غير موجود" description="اختر موضوعًا من مركز اكتشاف الروايات." action="تصفح الموضوعات" href="/topics" /></div>;
  return <div className="container py-10 md:py-16"><Breadcrumbs items={['الموضوعات', topic.title]} /><PageIntro eyebrow={topic.eyebrow} title={topic.title} description={topic.description} /><article className="rounded-[24px] border border-border bg-card p-6 text-sm leading-8 text-muted-foreground"><p>{topic.intro}</p></article><section className="mt-10"><h2 className="mb-5 text-xl font-extrabold">انتقل إلى المسارات المرتبطة</h2><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{topic.links.map((link) => <Link key={link.href} href={link.href} className="flex items-center justify-between rounded-2xl border border-border bg-card p-5 font-extrabold transition hover:-translate-y-1 hover:border-[#675de8]"><span className="flex items-center gap-3"><Tags className="text-[#675de8]" size={18} />{link.label}</span><ArrowLeft size={16} className="text-muted-foreground" /></Link>)}</div></section><section className="mt-12 rounded-[24px] bg-[#171e42] p-7 text-white"><h2 className="text-xl font-extrabold">ابنِ مسار قراءتك</h2><p className="mt-3 max-w-2xl text-sm leading-8 text-white/70">افتح أي رواية للوصول إلى مؤلفها واقتباساتها، أو انتقل إلى صفحة المؤلف لرؤية جميع أعماله، ثم تابع إلى السلسلة أو التصنيف المرتبط.</p><div className="mt-5 flex flex-wrap gap-3"><Link href="/explore" className="rounded-xl bg-white px-4 py-3 text-xs font-extrabold text-[#171e42]">استكشف الروايات</Link><Link href="/quotes" className="rounded-xl border border-white/20 px-4 py-3 text-xs font-extrabold">اقرأ الاقتباسات</Link></div></section></div>;
}

export default TopicsPage;
