import { sql } from 'drizzle-orm';
import { getDb } from './db';

type Row = Record<string, any>;
let schemaPromise: Promise<void> | null = null;

async function query<T extends Row = Row>(statement: ReturnType<typeof sql>) {
  const db = await getDb();
  if (!db) throw new Error('قاعدة البيانات غير متاحة');
  const result = await db.execute(statement);
  return (result as any).rows as T[];
}

export function ensureManagementSchema() {
  if (!schemaPromise) schemaPromise = (async () => {
    await query(sql`CREATE TABLE IF NOT EXISTS audit_logs (id serial primary key, actor_open_id varchar(160), actor_name text, action varchar(80) not null, entity_type varchar(80), entity_id varchar(160), details text, ip_address varchar(160), user_agent text, created_at timestamptz not null default now())`);
    await query(sql`CREATE TABLE IF NOT EXISTS trash_items (id serial primary key, entity_type varchar(80) not null, entity_id varchar(160) not null, label text not null, payload text not null, deleted_by varchar(160), deleted_at timestamptz not null default now(), restored_at timestamptz)`);
    await query(sql`CREATE TABLE IF NOT EXISTS notifications (id serial primary key, recipient_open_id varchar(160), recipient_role varchar(40), title varchar(255) not null, body text not null, link_url varchar(500), read_at timestamptz, created_by varchar(160), created_at timestamptz not null default now())`);
    await query(sql`ALTER TABLE notifications ADD COLUMN IF NOT EXISTS category varchar(40) not null default 'general'`);
    await query(sql`ALTER TABLE notifications ADD COLUMN IF NOT EXISTS color varchar(20) not null default '#675de8'`);
    await query(sql`ALTER TABLE notifications ADD COLUMN IF NOT EXISTS priority varchar(20) not null default 'normal'`);
    await query(sql`ALTER TABLE notifications ADD COLUMN IF NOT EXISTS scheduled_at timestamptz`);
    await query(sql`CREATE TABLE IF NOT EXISTS admin_messages (id serial primary key, recipient_type varchar(40) not null, recipient_open_id varchar(160), recipient_role varchar(40), subject varchar(255) not null, body text not null, sent_by varchar(160) not null, created_at timestamptz not null default now())`);
    await query(sql`CREATE TABLE IF NOT EXISTS advertisements (id serial primary key, title varchar(255) not null, body text, image_url varchar(500), link_url varchar(500), placement varchar(80) not null default 'home', status varchar(40) not null default 'draft', start_at timestamptz, end_at timestamptz, impressions integer not null default 0, clicks integer not null default 0, created_by varchar(160) not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now())`);
  })().catch((error) => { schemaPromise = null; throw error; });
  return schemaPromise;
}

export async function audit(actor: { openId: string; name?: string | null }, action: string, entityType?: string, entityId?: string, details?: unknown, req?: { ip?: string; headers?: Record<string, any> }) {
  await ensureManagementSchema();
  await query(sql`INSERT INTO audit_logs (actor_open_id, actor_name, action, entity_type, entity_id, details, ip_address, user_agent) VALUES (${actor.openId}, ${actor.name ?? null}, ${action}, ${entityType ?? null}, ${entityId ?? null}, ${details ? JSON.stringify(details) : null}, ${req?.ip ?? null}, ${req?.headers?.['user-agent'] ?? null})`);
}

export async function listAuditLogs(limit = 100) { await ensureManagementSchema(); return query(sql`SELECT id, actor_open_id AS "actorOpenId", actor_name AS "actorName", action, entity_type AS "entityType", entity_id AS "entityId", details, ip_address AS "ipAddress", user_agent AS "userAgent", created_at AS "createdAt" FROM audit_logs ORDER BY created_at DESC LIMIT ${limit}`); }
export async function listTrash() { await ensureManagementSchema(); return query(sql`SELECT id, entity_type AS "entityType", entity_id AS "entityId", label, payload, deleted_by AS "deletedBy", deleted_at AS "deletedAt", restored_at AS "restoredAt" FROM trash_items WHERE restored_at IS NULL ORDER BY deleted_at DESC`); }
export async function restoreTrash(id: number, actor: { openId: string; name?: string | null }) { await ensureManagementSchema(); const rows = await query(sql`SELECT entity_type AS "entityType", payload FROM trash_items WHERE id = ${id} AND restored_at IS NULL LIMIT 1`); const item = rows[0]; if (item?.entityType === 'advertisement' && item.payload) { const payload = typeof item.payload === 'string' ? JSON.parse(item.payload) : item.payload; await query(sql`INSERT INTO advertisements (id, title, body, image_url, link_url, placement, status, start_at, end_at, impressions, clicks, created_by, created_at, updated_at) VALUES (${payload.id}, ${payload.title}, ${payload.body ?? null}, ${payload.image_url ?? null}, ${payload.link_url ?? null}, ${payload.placement ?? 'home'}, ${payload.status ?? 'draft'}, ${payload.start_at ?? null}, ${payload.end_at ?? null}, ${payload.impressions ?? 0}, ${payload.clicks ?? 0}, ${payload.created_by ?? actor.openId}, ${payload.created_at ?? new Date()}, now()) ON CONFLICT (id) DO NOTHING`); } await query(sql`UPDATE trash_items SET restored_at = now() WHERE id = ${id} AND restored_at IS NULL`); await audit(actor, 'trash.restore', 'trash', String(id)); return { success: true }; }
export async function purgeTrash(id: number, actor: { openId: string; name?: string | null }) { await ensureManagementSchema(); await query(sql`DELETE FROM trash_items WHERE id = ${id}`); await audit(actor, 'trash.purge', 'trash', String(id)); return { success: true }; }

export async function listNotifications(openId: string, role: string) { await ensureManagementSchema(); return query(sql`SELECT id, title, body, link_url AS "linkUrl", category, color, priority, read_at AS "readAt", scheduled_at AS "scheduledAt", created_at AS "createdAt" FROM notifications WHERE (recipient_open_id = ${openId} OR recipient_role = 'all' OR recipient_role = ${role}) AND (scheduled_at IS NULL OR scheduled_at <= now()) ORDER BY created_at DESC LIMIT 100`); }
export async function markNotificationRead(id: number, openId: string) { await ensureManagementSchema(); await query(sql`UPDATE notifications SET read_at = now() WHERE id = ${id} AND (recipient_open_id = ${openId} OR recipient_role = 'all')`); return { success: true }; }
export async function createNotification(input: { recipientType: 'user' | 'role' | 'all'; recipientOpenId?: string; recipientRole?: string; title: string; body: string; linkUrl?: string; category?: string; color?: string; priority?: string; scheduledAt?: string }, actor: { openId: string; name?: string | null }) { await ensureManagementSchema(); await query(sql`INSERT INTO notifications (recipient_open_id, recipient_role, title, body, link_url, category, color, priority, scheduled_at, created_by) VALUES (${input.recipientType === 'user' ? input.recipientOpenId ?? null : null}, ${input.recipientType === 'role' ? input.recipientRole ?? null : input.recipientType === 'all' ? 'all' : null}, ${input.title}, ${input.body}, ${input.linkUrl ?? null}, ${input.category ?? 'general'}, ${input.color ?? '#675de8'}, ${input.priority ?? 'normal'}, ${input.scheduledAt ?? null}, ${actor.openId})`); await audit(actor, 'notification.create', 'notification', undefined, { title: input.title, recipientType: input.recipientType, category: input.category, priority: input.priority }); return { success: true }; }

export async function sendAdminMessage(input: { recipientType: 'users' | 'employees' | 'user'; recipientOpenId?: string; subject: string; body: string }, actor: { openId: string; name?: string | null }) { await ensureManagementSchema(); const role = input.recipientType === 'employees' ? 'employee' : null; await query(sql`INSERT INTO admin_messages (recipient_type, recipient_open_id, recipient_role, subject, body, sent_by) VALUES (${input.recipientType}, ${input.recipientType === 'user' ? input.recipientOpenId ?? null : null}, ${role}, ${input.subject}, ${input.body}, ${actor.openId})`); await audit(actor, 'message.send', 'message', undefined, { recipientType: input.recipientType, subject: input.subject }); return { success: true }; }
export async function listMessagesForUser(openId: string, isEmployee: boolean) { await ensureManagementSchema(); return query(sql`SELECT id, subject, body, created_at AS "createdAt" FROM admin_messages WHERE recipient_open_id = ${openId} OR recipient_type = 'users' OR (${isEmployee} AND recipient_role = 'employee') ORDER BY created_at DESC LIMIT 100`); }

export async function listAds() { await ensureManagementSchema(); return query(sql`SELECT id, title, body, image_url AS "imageUrl", link_url AS "linkUrl", placement, status, start_at AS "startAt", end_at AS "endAt", impressions, clicks, created_at AS "createdAt", updated_at AS "updatedAt" FROM advertisements ORDER BY updated_at DESC`); }
export async function createAd(input: { title: string; body?: string; imageUrl?: string; linkUrl?: string; placement: string; status: string; startAt?: string; endAt?: string }, actor: { openId: string; name?: string | null }) { await ensureManagementSchema(); const rows = await query(sql`INSERT INTO advertisements (title, body, image_url, link_url, placement, status, start_at, end_at, created_by) VALUES (${input.title}, ${input.body ?? null}, ${input.imageUrl ?? null}, ${input.linkUrl ?? null}, ${input.placement}, ${input.status}, ${input.startAt ?? null}, ${input.endAt ?? null}, ${actor.openId}) RETURNING id`); await audit(actor, 'ad.create', 'advertisement', String(rows[0]?.id), { title: input.title }); return rows[0]; }
export async function updateAd(id: number, input: Partial<{ title: string; body: string; imageUrl: string; linkUrl: string; placement: string; status: string; startAt: string; endAt: string }>, actor: { openId: string; name?: string | null }) { await ensureManagementSchema(); await query(sql`UPDATE advertisements SET title = COALESCE(${input.title ?? null}, title), body = COALESCE(${input.body ?? null}, body), image_url = COALESCE(${input.imageUrl ?? null}, image_url), link_url = COALESCE(${input.linkUrl ?? null}, link_url), placement = COALESCE(${input.placement ?? null}, placement), status = COALESCE(${input.status ?? null}, status), start_at = COALESCE(${input.startAt ?? null}, start_at), end_at = COALESCE(${input.endAt ?? null}, end_at), updated_at = now() WHERE id = ${id}`); await audit(actor, 'ad.update', 'advertisement', String(id), input); return { success: true }; }
export async function deleteAd(id: number, actor: { openId: string; name?: string | null }) { await ensureManagementSchema(); const rows = await query(sql`SELECT row_to_json(advertisements) AS payload, title FROM advertisements WHERE id = ${id}`); if (rows[0]) await query(sql`INSERT INTO trash_items (entity_type, entity_id, label, payload, deleted_by) VALUES ('advertisement', ${String(id)}, ${rows[0].title}, ${JSON.stringify(rows[0].payload)}, ${actor.openId})`); await query(sql`DELETE FROM advertisements WHERE id = ${id}`); await audit(actor, 'ad.delete', 'advertisement', String(id)); return { success: true }; }
export async function recordAdEvent(id: number, event: 'impression' | 'click') { await ensureManagementSchema(); await query(event === 'click' ? sql`UPDATE advertisements SET clicks = clicks + 1 WHERE id = ${id}` : sql`UPDATE advertisements SET impressions = impressions + 1 WHERE id = ${id}`); return { success: true }; }
export async function listActiveAds(placement: string) { await ensureManagementSchema(); return query(sql`SELECT id, title, body, image_url AS "imageUrl", link_url AS "linkUrl", placement FROM advertisements WHERE status = 'published' AND placement = ${placement} AND (start_at IS NULL OR start_at <= now()) AND (end_at IS NULL OR end_at >= now()) ORDER BY created_at DESC`); }

export async function getAdminReports() {
  await ensureManagementSchema();
  const [ads, activity, daily, topActors] = await Promise.all([
    query(sql`SELECT COALESCE(SUM(impressions), 0)::int AS impressions, COALESCE(SUM(clicks), 0)::int AS clicks, COUNT(*)::int AS campaigns, COUNT(*) FILTER (WHERE status = 'published')::int AS published FROM advertisements`),
    query(sql`SELECT action, COUNT(*)::int AS count FROM audit_logs GROUP BY action ORDER BY count DESC LIMIT 12`),
    query(sql`SELECT TO_CHAR(created_at AT TIME ZONE 'UTC', 'YYYY-MM-DD') AS day, COUNT(*) FILTER (WHERE action = 'auth.login')::int AS logins, COUNT(*)::int AS actions FROM audit_logs WHERE created_at >= now() - interval '14 days' GROUP BY day ORDER BY day`),
    query(sql`SELECT COALESCE(actor_name, actor_open_id) AS actor, COUNT(*)::int AS count FROM audit_logs GROUP BY actor_open_id, actor_name ORDER BY count DESC LIMIT 8`),
  ]);
  const summary = ads[0] ?? { impressions: 0, clicks: 0, campaigns: 0, published: 0 };
  return { summary, activity, daily, topActors };
}
