import { ArrowUpLeft, Facebook, MessageCircle } from 'lucide-react';
import { Link } from 'wouter';
import { Brand } from './Brand';

const email = 'shenuodaepraam@gmail.com';
const whatsappChannel = 'https://whatsapp.com/channel/0029Vb8nZiV4NViec0r66c0z';

export function SiteFooter() {
  return <footer className="mt-24 border-t border-border bg-card/55"><div className="container grid gap-10 py-14 md:grid-cols-[1.4fr_1fr_1fr_1fr] md:py-16"><div><Brand /><p className="mt-5 max-w-xs text-sm leading-7 text-muted-foreground">رِواية تساعدك تفهم عالم الروايات العربية، وتلاقي ما يستحق وقتك.</p><div className="mt-6 flex gap-2"><a href={`mailto:${email}`} className="grid size-9 place-items-center rounded-full border border-border text-muted-foreground hover:text-[#675de8]" aria-label="البريد الإلكتروني">@</a><a href={whatsappChannel} target="_blank" rel="noreferrer" className="grid size-9 place-items-center rounded-full border border-border text-muted-foreground hover:text-[#25d366]" aria-label="قناة واتساب"><MessageCircle size={15} /></a><a href="https://www.facebook.com/share/1EnkqsZn8e/" target="_blank" rel="noreferrer" className="grid size-9 place-items-center rounded-full border border-border text-muted-foreground hover:text-[#1877f2]" aria-label="فيسبوك"><Facebook size={15} /></a></div></div><div><h3 className="mb-4 text-sm font-extrabold">المنصة</h3><div className="grid gap-3 text-xs text-muted-foreground"><Link href="/about" className="hover:text-[#675de8]">عن رِواية</Link><Link href="/how-it-works" className="hover:text-[#675de8]">كيف تعمل المنصة؟</Link><Link href="/contact" className="hover:text-[#675de8]">تواصل معنا</Link></div></div><div><h3 className="mb-4 text-sm font-extrabold">استكشف</h3><div className="grid gap-3 text-xs text-muted-foreground"><Link href="/explore" className="hover:text-[#675de8]">كل الروايات</Link><Link href="/authors/amr-abdel-hamid" className="hover:text-[#675de8]">المؤلفون</Link><Link href="/genres/fantasy" className="hover:text-[#675de8]">التصنيفات</Link><Link href="/series/zikola" className="hover:text-[#675de8]">السلاسل</Link></div></div><div><h3 className="mb-4 text-sm font-extrabold">المساعدة</h3><div className="grid gap-3 text-xs text-muted-foreground"><Link href="/faq" className="hover:text-[#675de8]">الأسئلة الشائعة</Link><Link href="/report" className="hover:text-[#675de8]">الإبلاغ عن مشكلة</Link><Link href="/privacy" className="hover:text-[#675de8]">سياسة الخصوصية</Link><Link href="/terms" className="hover:text-[#675de8]">شروط الاستخدام</Link></div></div></div><div className="container flex flex-col justify-between gap-3 border-t border-border py-6 text-[11px] text-muted-foreground sm:flex-row"><span>© 2026 رِواية. منصة اكتشاف، لا تستضيف ملفات الكتب.</span><span className="flex items-center gap-1">صُنع بحب للقراءة <ArrowUpLeft size={13} className="text-[#675de8]" /></span></div></footer>;
}
